name: MinecraftInventoryLog
version: '${project.version}'
main: sinan.minecraftinventorylog.MinecraftInventoryLog
api-version: 1.17
authors: [ Sinan ]

# Replace "kit" with the name of your command.
commands:
  invrestore:
    description: Restores a previous inventory of a player.
    usage: /invrestore <player_name> <list | index>
    permission: sinan.inventoryrestore