name: MinecraftInventoryLog
version: '${project.version}'
main: sinanakkoyun.minecraftinventorylog.MinecraftInventoryLog
api-version: 1.17
authors: [ SinanAkkoyun ]

# Replace "kit" with the name of your command.
commands:
  restore:
    description: Restores a previous inventory of a player.
    usage: /restore <player_name> <list | index>
    permission: sinanakkoyun.inventoryrestore